HOST: http://www.fykovo.com/

--- Fyka test API v1 ---
---
Based on default API template v2
Welcome to the our sample API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
TODO's task Resources
The following is a section of resources related to the TODO app
--
List all tasks within db
GET /tasks
< 200
< Content-Type: application/json
{ "items": [
{ "url": "/tasks/1", "product":"2ZY48XPZ", "quantity": 1, "name": "New socks", "price": 1.25 }
] }


Create new task in our TODO app
POST /tasks
> Content-Type: application/json
{ "product":"1AB23ORM", "quantity": 2 }
< 201
< Content-Type: application/json
{ "status": "created", "url": "/tasks/2" }


-- Payment Resources --
This resource allows you to submit payment information to process your *shopping cart* items
POST /payment
{ "cc": "12345678900", "cvc": "123", "expiry": "0112" }
< 200
{ "receipt": "/payment/receipt/1" }